<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>fileTypes</key>
        <array>
                <string>lean</string>
                <string>hlean</string>
        </array>
        <key>name</key>
        <string>Lean</string>
        <key>patterns</key>
        <array>
                <dict>
                        <key>include</key>
                        <string>#dashComment</string>
                </dict>
                <dict>
                        <key>include</key>
                        <string>#blockComment</string>
                </dict>
                <dict>
                        <key>begin</key>
                        <string>^\s*(import)\b</string>
                        <key>beginCaptures</key>
                        <dict>
                                <key>1</key>
                                <dict>
                                        <key>name</key>
                                        <string>keyword.other.lean</string>
                                </dict>
                        </dict>
                        <key>end</key>
                        <string>$</string>
                        <key>name</key>
                        <string>meta.import.lean</string>
                        <key>patterns</key>
                        <array/>
                </dict>
                <dict>
                        <key>begin</key>
                        <string>\b(inductive|structure|record|theorem|proposition|axiom|axioms|lemma|hypothesis|definition|def|instance|class|constant)\b[ \t\n\r({\[]+([^ \t\n\r{(\[]*)</string>
                        <key>beginCaptures</key>
                        <dict>
                                <key>1</key>
                                <dict>
                                        <key>name</key>
                                        <string>keyword.other.lean</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                        <key>name</key>
                                        <string>variable.language.lean</string>
                                </dict>
                        </dict>
                        <key>end</key>
                        <string>[ \t\n\r{(\[]</string>
                        <key>name</key>
                        <string>meta.names.lean</string>
                        <key>pattern</key>
                        <array/>
                </dict>
                <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>name</key>
                        <string>string.quoted.double.lean</string>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>\\.</string>
                                        <key>name</key>
                                        <string>constant.character.escape.lean</string>
                                </dict>
                        </array>
                </dict>
                <dict>
                        <key>match</key>
                        <string>\b(Prop|Type[\'₊₀-₉]?)</string>
                        <key>name</key>
                        <string>storage.type.lean</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>@\[[^\]]*\]</string>
                        <key>name</key>
                        <string>storage.modifier.lean</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>attribute\s*\[[^\]]*\]</string>
                        <key>name</key>
                        <string>storage.modifier.lean</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>\b(import|prelude|theory|protected|private|noncomputable|mutual|meta|definition|def|instance|renaming|hiding|exposing|parameter|parameters|begin|conjecture|constant|constants|hypothesis|lemma|corollary|variable|variables|premise|premises|print|theorem|example|abbreviation|context|open|as|export|axiom|inductive|with|structure|record|universe|universes|alias|help|override|precedence|reserve|postfix|prefix|infix|infixl|infixr|notation|vm_eval|eval|check|exit|end|using|namespace|section|local|set_option|extends|include|omit|class|classes|instances|metaclasses|raw|run_command)\b</string>
                        <key>name</key>
                        <string>keyword.other.lean</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>\b(calc|have|assert|suppose|this|match|obtains|do|suffices|show|by|in|at|let|forall|fun|exists|if|then|else|assume|take|obtain|from)\b</string>
                        <key>name</key>
                        <string>keyword.other.lean</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>(-&gt;|==|:=|&lt;-&gt;|\\/|/\\|&lt;=|&gt;=|⁻¹)</string>
                        <key>name</key>
                        <string>constant.language.lua</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>[#@∼↔/=∧∨≠&lt;&gt;≤≥¬⬝▸+*-]</string>
                        <key>name</key>
                        <string>constant.language.lua</string>
                </dict>
                <dict>
                        <key>match</key>
                        <string>(?&lt;=\s)[=→λ∀?]</string>
                        <key>name</key>
                        <string>keyword.operator.lean</string>
                </dict>
                <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>beginCaptures</key>
                        <dict>
                                <key>0</key>
                                <dict>
                                        <key>name</key>
                                        <string>punctuation.definition.string.begin.lean</string>
                                </dict>
                        </dict>
                        <key>end</key>
                        <string>"</string>
                        <key>endCaptures</key>
                        <dict>
                                <key>0</key>
                                <dict>
                                        <key>name</key>
                                        <string>punctuation.definition.string.end.lean</string>
                                </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.double.lean</string>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\"'\&amp;])</string>
                                        <key>name</key>
                                        <string>constant.character.escape.lean</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>\\o[0-7]+|\\x[0-9A-Fa-f]+|\\[0-9]+</string>
                                        <key>name</key>
                                        <string>constant.character.escape.octal.lean</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>\^[A-Z@\[\]\\\^_]</string>
                                        <key>name</key>
                                        <string>constant.character.escape.control.lean</string>
                                </dict>
                        </array>
                </dict>
                <dict>
                        <key>match</key>
                        <string>\b([0-9]+|0([xX][0-9a-fA-F]+))\b</string>
                        <key>name</key>
                        <string>constant.numeric.lean</string>
                </dict>
        </array>
        <key>repository</key>
        <dict>
                <key>blockComment</key>
                <dict>
                        <key>begin</key>
                        <string>/-</string>
                        <key>captures</key>
                        <dict>
                                <key>0</key>
                                <dict>
                                        <key>name</key>
                                        <string>punctuation.definition.comment.lean</string>
                                </dict>
                        </dict>
                        <key>end</key>
                        <string>-/</string>
                        <key>name</key>
                        <string>comment.block.lean</string>
                </dict>
                <key>dashComment</key>
                <dict>
                        <key>begin</key>
                        <string>(--)</string>
                        <key>beginCaptures</key>
                        <dict>
                                <key>0</key>
                                <dict>
                                        <key>name</key>
                                        <string>punctuation.definition.comment.lean</string>
                                </dict>
                        </dict>
                        <key>end</key>
                        <string>$</string>
                        <key>name</key>
                        <string>comment.line.double-dash.lean</string>
                </dict>
                <key>identifier</key>
                <dict>
                        <key>comment</key>
                        <string>not so much here to be used as to be a reference</string>
                        <key>match</key>
                        <string>\b[^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*</string>
                        <key>name</key>
                        <string>entity.name.function.lean</string>
                </dict>
        </dict>
        <key>scopeName</key>
        <string>source.lean</string>
        <key>uuid</key>
        <string>BCCD7FA1-4C45-41B2-B1C9-C850F00AFCD8</string>
</dict>
</plist>
