name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute next version
        id: version
        run: |
          last_tag="$(git tag --sort=-v:refname --list 'v*' --no-contains | grep -v -- '-pre$' | head -1)"
          echo "Last release tag: $last_tag"
          last_version="${last_tag#v}"
          new_version="$(echo "$last_version" | awk -F. '{$NF=$NF+1; print}' OFS=.)"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Update version and create tag
        run: |
          new_version="${{ steps.version.outputs.new_version }}"
          sed -i 's/"version": ".*"/"version": "'$new_version'"/' vscode-lean4/package.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Release $new_version"
          git tag -a "v$new_version" -m "vscode-lean4 $new_version"

      - name: Push
        run: |
          git push
          git push --tags
